import Head from 'next/head';
import CardProfile from './components/Cards/CardProfile';
import CardSettings from './components/Cards/CardSettings';
import Navbar from './components/Navigations/NavBar';

const account = () => {
  return (
    <div className="flex">
      <Head>
        <title>Trading app</title>
        <meta name="React application which shows data obtained from apis. Users should be able to see: a list of all traders, a daily list of quotes, details of a specific trader, should be able to create a new trader/quote/withdrawal of funds" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-white dark:bg-gray-800 flex flex-col w-18 h-screen px-4 py-8 overflow-y-auto border-r">
        <div className="flex flex-col justify-between mt-2" style={{ height: "100%" }}>
          <Navbar />
        </div>
      </div>
      <div className="w-full h-full sm:p-4 md:p-8 overflow-y-auto">
        <div className=" items-center justify-center">
          <div className="flex flex-wrap">
            <div className="w-full lg:w-8/12 px-4">
              <CardSettings />
            </div>
            <div className="w-full lg:w-4/12 px-4">
              <CardProfile />
            </div>
          </div>

        </div>
      </div>

    </div>
  );
};

export default account;